repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff
        args: ["--fix", "website/", "config/", "tests/"]
        pass_filenames: false
      - id: ruff-format
        args: ["website/", "config/", "tests/"]
        pass_filenames: false

  - repo: https://github.com/jsh9/pydoclint
    rev: 0.8.6
    hooks:
      - id: pydoclint
        args: ["--style=google", "website/"]
        pass_filenames: false
