services:
  app:
    build:
      context: .
      target: app
    image: ghcr.io/club-jdr/questmaster:${TAG:-latest}
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
  app-test:
    build:
      context: .
      target: app-test
    volumes:
      - ./test-results:/questmaster/test-results/
    env_file:
      - .env
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
  db:
    image: postgres:15-alpine
    restart: always
    ports:
    - "5432:5432"
    env_file:
      - .env
    volumes:
    - db_data:/var/lib/postgresql/data
  redis: 
     image: redis:7.4-alpine
     restart: always
     ports:
       - '6379:6379' 
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8001:80"
    depends_on:
      - db
    links:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: club@jdr.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - pgadmin_data:/var/lib/pgadmin

volumes:
    db_data:
    pgadmin_data: