# Game Types
GAME_TYPE_ONESHOT = "oneshot"
GAME_TYPE_CAMPAIGN = "campaign"
GAME_TYPES = (GAME_TYPE_ONESHOT, GAME_TYPE_CAMPAIGN)

# Game Status
GAME_STATUS_DRAFT = "draft"
GAME_STATUS_OPEN = "open"
GAME_STATUS_CLOSED = "closed"
GAME_STATUS_ARCHIVED = "archived"
GAME_STATUS = (
    GAME_STATUS_DRAFT,
    GAME_STATUS_OPEN,
    GAME_STATUS_CLOSED,
    GAME_STATUS_ARCHIVED,
)

# Game Frequencies
GAME_FREQ_WEEKLY = "weekly"
GAME_FREQ_BI_WEEKLY = "bi-weekly"
GAME_FREQ_MONTHLY = "monthly"
GAME_FREQ_OTHER = "other"
GAME_FREQUENCIES = (
    GAME_FREQ_WEEKLY,
    GAME_FREQ_BI_WEEKLY,
    GAME_FREQ_MONTHLY,
    GAME_FREQ_OTHER,
)

# Experience Levels
GAME_XP_ALL = "all"
GAME_XP_BEGINNERS = "beginners"
GAME_XP_SEASONED = "seasoned"
GAME_XP = (GAME_XP_ALL, GAME_XP_BEGINNERS, GAME_XP_SEASONED)

# Character Creation
GAME_CHAR_WITH_GM = "with_gm"
GAME_CHAR_SELF = "self"
GAME_CHAR_PREGEN = "pregen"
GAME_CHAR_CHOICE = "choice"
GAME_CHAR = (
    GAME_CHAR_WITH_GM,
    GAME_CHAR_SELF,
    GAME_CHAR_PREGEN,
    GAME_CHAR_CHOICE,
)

# Restrictions
RESTRICTION_ALL = "all"
RESTRICTION_16_PLUS = "16+"
RESTRICTION_18_PLUS = "18+"
RESTRICTIONS = (RESTRICTION_ALL, RESTRICTION_16_PLUS, RESTRICTION_18_PLUS)

# Ambiences
AMBIENCE_CHILL = "chill"
AMBIENCE_SERIOUS = "serious"
AMBIENCE_COMIC = "comic"
AMBIENCE_EPIC = "epic"
AMBIENCES = (
    AMBIENCE_CHILL,
    AMBIENCE_SERIOUS,
    AMBIENCE_COMIC,
    AMBIENCE_EPIC,
)

# Event Actions
EVENT_ACTION_CREATE = "create"
EVENT_ACTION_EDIT = "edit"
EVENT_ACTION_DELETE = "delete"
EVENT_ACTION_CREATE_SESSION = "create-session"
EVENT_ACTION_EDIT_SESSION = "edit-session"
EVENT_ACTION_DELETE_SESSION = "delete-session"
EVENT_ACTION_REGISTER = "register"
EVENT_ACTION_UNREGISTER = "unregister"
EVENT_ACTION_ALERT = "alert"
EVENT_ACTIONS = (
    EVENT_ACTION_CREATE,
    EVENT_ACTION_EDIT,
    EVENT_ACTION_DELETE,
    EVENT_ACTION_CREATE_SESSION,
    EVENT_ACTION_EDIT_SESSION,
    EVENT_ACTION_DELETE_SESSION,
    EVENT_ACTION_REGISTER,
    EVENT_ACTION_UNREGISTER,
    EVENT_ACTION_ALERT,
)

# Badge IDs
BADGE_OS_ID = 1
BADGE_OS_GM_ID = 2
BADGE_CAMPAIGN_ID = 3
BADGE_CAMPAIGN_GM_ID = 4

# Discord
DEFAULT_AVATAR = "/static/img/avatar.webp"
AVATAR_BASE_URL = "https://cdn.discordapp.com/avatars/{}/{}"

# Pagination
GAMES_PER_PAGE = 12

# Routes
GAME_DETAILS_ROUTE = "annonces.get_game_details"
SEARCH_GAMES_ROUTE = "annonces.search_games"
